swagger: '2.0'
info:
  title: XSS Test API
  version: 1.0.0
paths:
  /:
    get:
      summary: XSS testing
      description: |
        <img src=x onerror="alert('XSS')">
      responses:
        '200':
          description: Successful response
