swagger: '2.0'
info:
  title: XSS Test 
  version: 1.0.0
paths:
  /:
    get:
      summary: XSS testing
      description: |
     <img src="data:image/svg+xml;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=">

      responses:
        '200':
          description: Successful response
