swagger: '2.0'
info:
  title: XSS Test API
  version: 1.0.0
paths:
  /:
    get:
      summary: XSS testing
      description: |
        <script>alert('XSS')</script>
      responses:
        '200':
          description: Successful response
